CREATE TABLE sizes (
  id SERIAL PRIMARY KEY,
  label VARCHAR(20) NOT NULL,
  system VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (label, system)
);
