CREATE TABLE sizes (
  id SERIAL PRIMARY KEY,
  label VARCHAR(20) NOT NULL,
  system VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (label, system)
);

ALTER TABLE sizes ADD COLUMN location VARCHAR(10);
ALTER TABLE sizes ADD COLUMN stock INTEGER DEFAULT 0;
