export const categoryConfig = {
  "women-superstar": {
    title: "Women's Superstar Shoes",
    breadcrumb: "Home / Women / Superstar",
    description:
      "Make the world your stage in women’s Superstar shoes. Go for a bold design to bring modern energy to an iconic look or keep it lowkey with your favorite colorway for a classic vibe.",
    category: "women",
    subcategory: "running",
    productType: "shoes",
    totalProducts: 26,
  },
  "men-superstar": {
    title: "Men's adidas Superstar Shoes",
    breadcrumb: "Home / Men / Superstar",
    description:
      "From their 1969 NBA debut to hip-hop cult classic, the adidas men's superstar shoes have become true shoe icons. Featuring famous shell-toe design.",
    category: "men",
    subcategory: "running",
    productType: "shoes",
    totalProducts: 35,
  },
  "kids-superstar": {
    title: "Kids' Superstar Shoes",
    breadcrumb: "Home / Kids / Superstar",
    description: "adidas superstar shoes first debuted on the basketball court and have been an icon ever since. Our kids' superstar shoes feature the classic silhouette in a variety of colors, from black and white to metallic.",
    category: "kids",
    subcategory: "soccer",
    productType: "shoes",
    totalProducts: 58,
  },
  "men-soccer-shoes": {
    title: "MEN'S SOCCER SHOES",
    breadcrumb: "Men / Soccer / Shoes",
    description:
      "Find your perfect pair of men's soccer shoes. From firm ground to artificial turf, we have the right cleats for every playing surface.",
    category: "men",
    subcategory: "soccer",
    productType: "shoes",
    totalProducts: 156,
  },
  "men-tops": {
    title: "MEN'S TOPS",
    breadcrumb: "Men / Clothing / Tops",
    description:
      "Discover our collection of men's tops. From t-shirts to tank tops, find the perfect fit for your active lifestyle.",
    category: "men",
    subcategory: "clothing",
    productType: "tops",
    totalProducts: 89,
  },
  "women-running-shoes": {
    title: "WOMEN'S RUNNING SHOES",
    breadcrumb: "Women / Running / Shoes",
    description:
      "Step up your running game with our women's running shoes. Designed for comfort, performance and style.",
    category: "women",
    subcategory: "running",
    productType: "shoes",
    totalProducts: 124,
  },
  "kids-soccer-shoes": {
    title: "KIDS' SOCCER SHOES",
    breadcrumb: "Kids / Soccer / Shoes",
    description: "Get your young athlete ready for the field with our kids' soccer shoes collection.",
    category: "kids",
    subcategory: "soccer",
    productType: "shoes",
    totalProducts: 67,
  },
  "new-arrivals": {
    title: "NEW ARRIVALS",
    breadcrumb: "Home / New Arrivals",
    description:
      "Discover the latest products from adidas. Fresh styles, innovative technology, and cutting-edge design.",
    category: "new-arrivals",
    subcategory: "",
    productType: "",
    totalProducts: 245,
  },
  "best-sellers": {
    title: "BEST SELLERS",
    breadcrumb: "Home / Best Sellers",
    description: "Shop our most popular products. These customer favorites are flying off the shelves.",
    category: "best-sellers",
    subcategory: "",
    productType: "",
    totalProducts: 189,
  },
  sale: {
    title: "SALE",
    breadcrumb: "Home / Sale",
    description: "Save big on adidas favorites. Limited time offers on shoes, clothing, and accessories.",
    category: "sale",
    subcategory: "",
    productType: "",
    totalProducts: 312,
  },
  prime: {
    title: "PRIME FAST & FREE DELIVERY",
    breadcrumb: "Home / Prime",
    description: "Get your adidas favorites delivered fast and free with Prime eligible products.",
    category: "prime",
    subcategory: "",
    productType: "",
    totalProducts: 156,
  },
}
