ALTER TABLE users ADD COLUMN IF NOT EXISTS is_staff BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_joined TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_superuser BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users
ADD COLUMN IF NOT EXISTS password VARCHAR NOT NULL
DEFAULT 'pbkdf2_sha256$720000$mf7gOJi6b6lcClmMxd0UaY$JEXwqKpSjnuNmBE42U9DFtjLO6x2fIPCnOQ9oA59iHo=';

ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR NOT NULL DEFAULT '';

ALTER TABLE users ADD COLUMN IF NOT EXISTS admin BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE accounts_user
ALTER COLUMN admin DROP NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS activated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activated_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_sent_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE users ADD COLUMN IF NOT EXISTS remember_digest VARCHAR NOT NULL;

ALTER TABLE accounts_user
ALTER COLUMN remember_digest DROP NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS activation_digest VARCHAR NOT NULL;

ALTER TABLE accounts_user
ALTER COLUMN activation_digest DROP NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_digest VARCHAR NOT NULL;

ALTER TABLE accounts_user
ALTER COLUMN reset_digest DROP NOT NULL;
